service: express-blog-app

frameworkVersion: '4.10.1'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  timeout: 29
  apiGateway:
    binaryMediaTypes:
      - '*/*'
      - 'multipart/form-data'
      - 'image/jpeg'
      - 'image/png'
      - 'image/webp'
      - 'image/gif'
      - 'application/pdf'
      - 'video/quicktime'
      - 'video/mp4'
      - 'video/webm'
  environment:
    MONGO_URI: ${env:MONGO_URI}
    SECRET_KEY: ${env:SECRET_KEY}
    ADMIN_USERNAME: ${env:ADMIN_USERNAME}
    ADMIN_PASSWORD: ${env:ADMIN_PASSWORD}
    FRED_API: ${env:FRED_API}

functions:
  serveImage:
    handler: binaryImage.handler
    events:
      - http:
          path: static/{proxy+}
          method: get
      - http:
          path: data/{proxy+}
          method: get

  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
          request:
            parameters:
              paths:
                proxy:
                  # only match if proxy does NOT start with "static/" or "data/"
                  pattern: '^(?!static/|data/).+$'

  fetchDashboard:
    name: express-blog-app-dev-fetchDashboard
    handler: py_fetcher/handler.run
    runtime: python3.11
    timeout: 30
    memorySize: 512
    environment:
      MONGO_URI: ${env:MONGO_URI}
      SECRET_KEY: ${env:SECRET_KEY}
      ADMIN_USERNAME: ${env:ADMIN_USERNAME}
      ADMIN_PASSWORD: ${env:ADMIN_PASSWORD}
      FRED_API: ${env:FRED_API}

plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  customDomain:
    domainName: iivashch.click
    basePath: ''
    stage: dev
    createRoute53Record: true
    endpointType: regional
  dotenv:
    basePath: ./
  pythonRequirements:
    pythonBin: python3

package:
  include:
    - 'public/data/**'
    - 'binaryImage.js'
  patterns:
    - '!node_modules/**'
    - 'node_modules/express/**'
    - 'node_modules/**'
    - 'app.js'
    - 'lambda.js'
    - 'routes/**'
    - 'models/**'
    - 'middleware/**'
    - 'views/**'
  exclude:
    - .git/**
    - .gitignore
    - README.md
    - .vscode/
    - .env
    - .DS_Store
